---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: \.js$
        args:
          - --license-filepath
          - ./license_header.txt
          - --comment-style
          - // # defaults to:  #
      - id: insert-license
        files: \.ts$
        args:
          - --license-filepath
          - ./license_header.txt
          - --comment-style
          - // # defaults to:  #

    # The maintainer of this is particularly unhelpful,
    # consider using a fork or a local version instead.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.7
        files: '\.(js?|ts?)$'
