services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '1884:1884'
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - $ZIGBEE2MQTT_CONFIG_SERIAL_PORT:$ZIGBEE2MQTT_CONFIG_SERIAL_PORT
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/London
    env_file:
      - .env

  webserver:
    container_name: zigbee_webui
    image: ghcr.io/amberstarlight/zigbee-webui:latest
    ports:
      - '80:80'
