FROM node:lts-alpine AS build
WORKDIR /app
COPY ./ /app/
ENV NODE_ENV production
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine AS production
LABEL org.opencontainers.image.source="https://github.com/amberstarlight/starlight"
COPY --from=build /app/build /usr/share/nginx/html
COPY .nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
