services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - $ZIGBEE2MQTT_CONFIG_SERIAL_PORT:$ZIGBEE2MQTT_CONFIG_SERIAL_PORT
    restart: always
    network_mode: host
    privileged: true
    environment:
      TZ: "Europe/London"
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "/dev/ttyUSB0"
      ZIGBEE2MQTT_CONFIG_ADVANCED_RTSCTS: "false"
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_CONFIG_AVAILABILITY: "true"

  api:
    container_name: starlight_api
    image: ghcr.io/amberstarlight/starlight/ui:latest
    ports:
      - "80:80"

  ui:
    container_name: starlight_ui
    image: gchr.io/amberstarlight/starlight/api:latest
    ports:
      - "80:80"
