name: Lint

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Latest Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: latest

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run Linting
        run: yarn prettier -c .
