name: Lint

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: "yarn"

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run Linting
        run: yarn prettier -c .
